### PR TITLE
Update dependency seneca-crypto-sign to 0.1.2

### PR DESCRIPTION
**Pull request by razvanz**
And bump & release  `0.2.17` afterwards. Thanks!

### CODE REVIEW

**Comment by razvanz** [comment]
Right. I forgot that this is strictly for `node >=0.12`, therefore is normal to fail on `v0.11`. Would you consider another version minor: `0.3` for the release?

**Comment by nherment** [comment]
@razvanz version bump plz for making my life easier.
Also please ping me on nearform mail or slack for private conv.

**Comment by razvanz** [comment]
What is your nearform mail? Or should I send to the public one (ireland@nearform.com)?

**Comment by nherment** [comment]
nicolas.herment at nearform d0t c0m

**Comment by razvanz** [comment]
Not relevant for `0.2-dev`.

**Pull request closed without merging**
